name: my_architecture_mobx
description: A new Flutter project.
homepage: www.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  # Language 
  # Required Ios Info.plist
  easy_localization: ^3.0.0
  # Security 
  # Android Backup Disabled
  flutter_secure_storage: ^5.0.2
  # Storage
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  # Generator
  json_annotation: ^4.4.0
  # Core
  get_it: ^7.2.0
  kartal: ^2.3.1
  logger: ^1.1.0
  # State Management
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  # Utils
  turkish: ^0.2.1
  intl: ^0.17.0
  another_flushbar: ^1.10.28
  # Network
  vexana: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linter
  flutter_lints: ^1.0.4
  # Generator
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  json_serializable: ^6.1.5
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/language/
    - assets/icon/
